### ISSUE TITLE
invalid meeting code

### ISSUE THREAD

**Issue by csonuryilmaz** [SrMouraSilva/google-meet-plugin#1]
Hi, I've installed plugin to Mattermost `5.22.2` successfully.

Plugin button is visible. Whwn I click button, it generates the link below:
- http://g.co/meet/e9d11670-fa85-4be6-8fad-305cf2abde9f

But when I click on this URL, Google Meet gives error:

<kbd><img width="800" alt="Screen Shot 2021-01-15 at 23 45 00" src="https://user-images.githubusercontent.com/7355362/104777387-9e6e5180-578c-11eb-8850-b6b39bb449e8.png"></kbd>

Generated meeting code seems to be invalid. 🤔

**Comment by SrMouraSilva** [comment]
Hi @csonuryilmaz 

This plugin only generates a random `UUID` and presents a button with `http://g.co/meet/<UUID generated>`

I'm check here and, when I select an @gmail.com account after click this link, appears the same message, but if I select an @myrandomcompany.com (that uses [G Suite for Education](https://edu.google.com/intl/en-US/products/gsuite-for-education/)), this link works.

I give this create meet room strategy from [stackoverflow](https://stackoverflow.com/a/62313196/1524997). [As as person talked](https://stackoverflow.com/questions/61216047/is-there-direct-api-for-google-meet#comment111131785_62313196), doesn't works in @gmail.com personal accounts. This is a bad news. I think that works in any type of account.
